//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.UI.MVC.MantenimientosServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MantenimientosServices.IMantenimientosServices")]
    public interface IMantenimientosServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/GetCustomers", ReplyAction="http://tempuri.org/IMantenimientosServices/GetCustomersResponse")]
        System.Collections.Generic.List<App.Entities.Base.Customer> GetCustomers(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/GetCustomers", ReplyAction="http://tempuri.org/IMantenimientosServices/GetCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.Entities.Base.Customer>> GetCustomersAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/GetArtistAll", ReplyAction="http://tempuri.org/IMantenimientosServices/GetArtistAllResponse")]
        System.Collections.Generic.List<App.Entities.Base.Artist> GetArtistAll(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/GetArtistAll", ReplyAction="http://tempuri.org/IMantenimientosServices/GetArtistAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<App.Entities.Base.Artist>> GetArtistAllAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/SaveArtist", ReplyAction="http://tempuri.org/IMantenimientosServices/SaveArtistResponse")]
        bool SaveArtist(App.Entities.Base.Artist entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/SaveArtist", ReplyAction="http://tempuri.org/IMantenimientosServices/SaveArtistResponse")]
        System.Threading.Tasks.Task<bool> SaveArtistAsync(App.Entities.Base.Artist entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/GetArtist", ReplyAction="http://tempuri.org/IMantenimientosServices/GetArtistResponse")]
        App.Entities.Base.Artist GetArtist(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/GetArtist", ReplyAction="http://tempuri.org/IMantenimientosServices/GetArtistResponse")]
        System.Threading.Tasks.Task<App.Entities.Base.Artist> GetArtistAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/SaveInvoice", ReplyAction="http://tempuri.org/IMantenimientosServices/SaveInvoiceResponse")]
        int SaveInvoice(App.Entities.Base.Invoice entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMantenimientosServices/SaveInvoice", ReplyAction="http://tempuri.org/IMantenimientosServices/SaveInvoiceResponse")]
        System.Threading.Tasks.Task<int> SaveInvoiceAsync(App.Entities.Base.Invoice entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMantenimientosServicesChannel : App.UI.MVC.MantenimientosServices.IMantenimientosServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MantenimientosServicesClient : System.ServiceModel.ClientBase<App.UI.MVC.MantenimientosServices.IMantenimientosServices>, App.UI.MVC.MantenimientosServices.IMantenimientosServices {
        
        public MantenimientosServicesClient() {
        }
        
        public MantenimientosServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MantenimientosServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientosServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MantenimientosServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<App.Entities.Base.Customer> GetCustomers(string nombre) {
            return base.Channel.GetCustomers(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.Entities.Base.Customer>> GetCustomersAsync(string nombre) {
            return base.Channel.GetCustomersAsync(nombre);
        }
        
        public System.Collections.Generic.List<App.Entities.Base.Artist> GetArtistAll(string nombre) {
            return base.Channel.GetArtistAll(nombre);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<App.Entities.Base.Artist>> GetArtistAllAsync(string nombre) {
            return base.Channel.GetArtistAllAsync(nombre);
        }
        
        public bool SaveArtist(App.Entities.Base.Artist entity) {
            return base.Channel.SaveArtist(entity);
        }
        
        public System.Threading.Tasks.Task<bool> SaveArtistAsync(App.Entities.Base.Artist entity) {
            return base.Channel.SaveArtistAsync(entity);
        }
        
        public App.Entities.Base.Artist GetArtist(int id) {
            return base.Channel.GetArtist(id);
        }
        
        public System.Threading.Tasks.Task<App.Entities.Base.Artist> GetArtistAsync(int id) {
            return base.Channel.GetArtistAsync(id);
        }
        
        public int SaveInvoice(App.Entities.Base.Invoice entity) {
            return base.Channel.SaveInvoice(entity);
        }
        
        public System.Threading.Tasks.Task<int> SaveInvoiceAsync(App.Entities.Base.Invoice entity) {
            return base.Channel.SaveInvoiceAsync(entity);
        }
    }
}
